vich_uploader:
    db_driver: orm

    mappings:
       annonce:
            uri_prefix: /images/annonce
            upload_destination: '%kernel.project_dir%/public/images/annonce'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
